package es.danibeni.android.kotlin.rctelemetry.core.constants

class Constants {
    companion object {
        const val RCTELEMETRY_AP_PREFIX = "RCTELEMETRY"
        const val RCTELEMETRY_VEHICLE_PREFIX="RCTELEMETRY_VEHICLE"
        const val RCTELEMETRY_VEHICLE_PORT = 60001
        const val RCTELEMETRY_IP_RANGE_LOWEST = 100
        const val RCTELEMETRY_IP_RANGE_HIGHEST = 110

        const val RCTELEMETRY_RESPONSE_ACK = "ACK"
        const val CHANGE_WIFI_NETWORK_CONNECTION = 1
        const val RCTELEMETRY_IDENTIFY_VEHICLE_TIMEOUT = 6000

        const val RCTELEMETRY_VEHICLE_WIFI_STRENGTH_OK = -70
        const val RCTELEMETRY_VEHICLE_WIFI_STRENGTH_WARN = -90
        const val RCTELEMETRY_VEHICLE_WIFI_STRENGTH_THRESHOLD_PERIOD_MS = 2000
        const val RCTELEMETRY_VEHICLE_WIFI_STRENGTH_REFRESH_TIME_MS = 200
        const val RCTELEMETRY_VEHICLE_WIFI_STRENGTH_MAX_COMM_ERROR = 5
        const val RCTELEMETRY_VEHICLE_WIFI_STRENGTH_THRESHOLD_MARGIN = 8
        const val RCTELEMETRY_VEHICLE_WIFI_STRENGTH_SKIP_PERIOD_MS = 10000
    }
}